---
- name: Install docker and run the app container
  hosts: 192.168.10.130
  remote_user: asmaa
  become: yes
  become_method: sudo
  tasks:
  - name: Install Docker
    shell: cd ~ && curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh
